### ISSUE TITLE
Verify on the different naming

### ISSUE THREAD

**Issue by yong2khoo-lm** [ilharp/sign-android-release#14]
Here I have question on the output file naming

<img width="310" alt="image" src="https://user-images.githubusercontent.com/51041738/219267622-f849dd02-41e3-4838-81b8-52a62d4bae69.png">

As noticed, the output files contain:
### APK
```
...unsigned-signed.apk
...signed.apk
```

### AAB
```
...signed.aab
...aab
...-temp.aab
```

Can i assume that, the `-signed.apk` and `-signed.aab` are the final one?

**Comment by ilharp** [comment]
Currently, yes. The signed file will be suffixed with `-signed`, such as `app.apk` => `app-signed.apk`.

But a better solution is to use the `signedFile` / `signedFiles` output of this action, as shown in [README](https://github.com/ilharp/sign-android-release#usage). You can also find more practical examples [here](https://github.com/ilharp/sign-android-release/network/dependents) and [here](https://github.com/search?q=ilharp%2Fsign-android-release+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&s=indexed&o=desc).

Feel free to reopen this issue if you have any other questions.
