### ISSUE TITLE
zipalign not found on windows-latest runner

### ISSUE THREAD

**Issue by EMarshal** [ilharp/sign-android-release#3]
I'm running into `Error: Exception: Cannot find zipalign. Please setup Android before this action.` with the windows-latest build image and the default build tools version - could this be related to the zipalign binary being `zipalign.exe` on Windows? (The zipalign binary should be present - the https://github.com/r0adkll/sign-android-release step is able to execute it in the same workflow.)

**Comment by ilharp** [comment]
Sorry for not replying in time. This might indeed have something to do with the missing ".exe".

**Comment by ilharp** [comment]
Bugfix commit pushed. You can try the nightly version and I'll release a new version soon.

```yml
- uses: ilharp/sign-android-release@nightly
```

**Comment by ilharp** [comment]
`v1.0.2` released. It's now safe to revert to `v1`. If you encounter other problems, please create a new issue.
