### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by daywalk3r666** [ilharp/sign-android-release#9]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![Screenshot_20221019-200604_Trebuchet](https://user-images.githubusercontent.com/15938117/196771196-5e5fba35-69d2-48fb-bd8c-4fbed483574a.png)

**Comment by ilharp** [comment]
Thanks. Investigating now.

**Comment by harry248** [comment]
Just wanted to ask if there are any news on this. Thanks!

**Comment by ilharp** [comment]
[v1.0.3](https://github.com/ilharp/sign-android-release/releases/tag/v1.0.3) published. If you are using `v1`, next time you run the workflow it will automatically use the latest version. If you have other questions, feel free to reopen this issue.

**Comment by daywalk3r666** [comment]
The v1.0.3 release won't fix the issue. I think https://github.com/ilharp/sign-android-release/blob/3eb1dc9466aa3e26c2877724598e56655c7ebe7c/src/main/kotlin/Main.kt#L87 this must update and update core

**Comment by ilharp** [comment]
Investigating.

**Comment by ilharp** [comment]
[v1.0.4](https://github.com/ilharp/sign-android-release/releases/tag/v1.0.4) published. If you are using `v1`, next time you run the workflow it will automatically use the latest version. If you have other questions, feel free to reopen this issue.

**Comment by daywalk3r666** [comment]
My pull request only fix your build action.

**Comment by david-potgieter** [comment]
> [v1.0.4](https://github.com/ilharp/sign-android-release/releases/tag/v1.0.4) published. If you are using `v1`, next time you run the workflow it will automatically use the latest version. If you have other questions, feel free to reopen this issue.

I missed that, thank you for catching and fixing.
